name: main

on: [push]

jobs:
  score:
    runs-on: ubuntu-latest
    steps:
    - uses: Wizkas0/ScoreBoard@main
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        something: "false"
