name: main

on: [push]

jobs:
  score:
    runs-on: ubuntu-latest
    steps:
    - uses: ./example-integration
    - uses: Wizkas0/ScoreBoard@main
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        new-scores: ${{ steps.commit-scores.outputs.scores }}
