name: main

on: [push]

jobs:
  score-commits:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Example integration
      id: commit-scores
      uses: ./example-integration
      with:
        min-word-count: "5"
    - uses: Wizkas0/ScoreBoard@main
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        new-scores: ${{ steps.commit-scores.outputs.scores }}
